version: '2'
services:
  web:
    build: .
    links:
      - postgres
    environment:
      DATABASE_URL: "postgres://todoapp@postgres/todos"
    cached: true
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: todoapp
      POSTGRES_DB: todos
    cached: true
  deploy:
    image: codeship/heroku-deployment
    encrypted_env_file: deployment.env.encrypted
    volumes:
      - ./:/deploy
